/**
 * AI-generated graphic template types and Redis helpers.
 *
 * Templates are generated by Claude from a style prompt and stored in Redis.
 * The DynamicGraphic component renders any GraphicConfig at any canvas size.
 *
 * Key namespace: cms:graphic-template:{id}
 * Index key:     cms:graphic-template:index  (string[] of ids, newest first)
 */

import { getRedis } from "@/lib/upstash";

const TTL = 365 * 24 * 3600;

// ── Types ──────────────────────────────────────────────────────────────────────

export type PatternType = "none" | "grid" | "honeycomb" | "stars" | "scanlines" | "dots";
export type FontStyle = "sans" | "script";
export type TextAlign = "left" | "center" | "right";
export type LogoVariant = "white" | "orange" | "green";
export type LetterTracking = "tight" | "normal" | "wide" | "ultra-wide";
export type FontWeight = "normal" | "bold" | "black";

export interface GraphicConfigBackground {
  color: string;
  pattern?: PatternType;
  patternColor?: string;
  patternOpacity?: number;
  gradient?: {
    type: "radial" | "linear";
    from: string;
    to: string;
    angle?: number;  // degrees, linear only
    cx?: number;     // 0-100, radial only
    cy?: number;     // 0-100, radial only
  };
}

export interface GraphicConfigGlow {
  color: string;
  cx: number;    // 0-100 (% of canvas width)
  cy: number;    // 0-100 (% of canvas height)
  radius: number; // 0-100 (% of canvas width)
  opacity: number; // 0-1
}

export interface GraphicConfigHeadline {
  lines: string[];
  color: string;
  /** Font size as fraction of canvas HEIGHT, e.g. 0.28 → 28% of height */
  size: number;
  fontStyle: FontStyle;
  tracking: LetterTracking;
  weight: FontWeight;
  /** 0-100. For left: left edge. For center: center point. For right: right edge. */
  x: number;
  /** 0-100 (% of canvas height, top of first line) */
  y: number;
  align: TextAlign;
  uppercase?: boolean;
}

export interface GraphicConfigShape {
  type: "circle" | "ring" | "line" | "rect";
  // circle/ring: cx, cy (0-100), r (% of canvas width)
  cx?: number;
  cy?: number;
  r?: number;
  // line: x1,y1,x2,y2 (0-100)
  x1?: number; y1?: number; x2?: number; y2?: number;
  // rect: x,y,w,h (0-100)
  x?: number; y?: number; w?: number; h?: number;
  color: string;
  opacity: number; // 0-1
  fill?: boolean;  // false = stroke only
  /** Stroke width as % of canvas width, e.g. 0.003 */
  strokeWidth?: number;
}

export interface GraphicConfigLogo {
  variant: LogoVariant;
  /** 0-100 (top-left corner of logo, % of canvas) */
  x: number;
  y: number;
  /** Logo size as % of canvas WIDTH, e.g. 0.065 */
  size: number;
}

export interface GraphicConfigSubtitle {
  text: string;
  color: string;
  /** Font size as fraction of canvas HEIGHT */
  size: number;
  x: number;
  y: number;
  tracking?: "normal" | "wide";
  uppercase?: boolean;
}

export interface GraphicConfig {
  id: string;
  name: string;
  /** Event type slug this template applies to, e.g. "chamber-chat" */
  eventTypeSlug: string;
  createdAt: string;
  stylePrompt: string;

  background: GraphicConfigBackground;
  glows?: GraphicConfigGlow[];
  headline: GraphicConfigHeadline;
  shapes?: GraphicConfigShape[];
  logo: GraphicConfigLogo;
  subtitle?: GraphicConfigSubtitle;
}

/** The fields Claude generates — id/createdAt added server-side */
export type GraphicConfigDraft = Omit<GraphicConfig, "id" | "createdAt">;

// ── Redis helpers ──────────────────────────────────────────────────────────────

export async function saveGraphicTemplate(config: GraphicConfig): Promise<void> {
  const redis = getRedis();
  if (!redis) throw new Error("Redis not configured");
  await redis.set(`cms:graphic-template:${config.id}`, config, { ex: TTL });
  const ids = (await redis.get<string[]>("cms:graphic-template:index")) ?? [];
  if (!ids.includes(config.id)) {
    await redis.set("cms:graphic-template:index", [config.id, ...ids], { ex: TTL });
  }
}

export async function getGraphicTemplate(id: string): Promise<GraphicConfig | null> {
  const redis = getRedis();
  if (!redis) return null;
  return redis.get<GraphicConfig>(`cms:graphic-template:${id}`);
}

export async function listGraphicTemplates(): Promise<GraphicConfig[]> {
  const redis = getRedis();
  if (!redis) return [];
  const ids = (await redis.get<string[]>("cms:graphic-template:index")) ?? [];
  const templates = await Promise.all(ids.map(getGraphicTemplate));
  return templates.filter((t): t is GraphicConfig => t !== null);
}

export async function deleteGraphicTemplate(id: string): Promise<void> {
  const redis = getRedis();
  if (!redis) return;
  await redis.del(`cms:graphic-template:${id}`);
  const ids = (await redis.get<string[]>("cms:graphic-template:index")) ?? [];
  await redis.set(
    "cms:graphic-template:index",
    ids.filter((i) => i !== id),
    { ex: TTL },
  );
}

/** Returns the most recently saved template for a given event type, or null. */
export async function getTemplateForEventType(eventTypeSlug: string): Promise<GraphicConfig | null> {
  const all = await listGraphicTemplates();
  return all.find((t) => t.eventTypeSlug === eventTypeSlug) ?? null;
}
